---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: regression_model-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: regression_model-webapp
  template:
    metadata:
      labels:
        app: regression_model-webapp
    spec:
      containers:
      - name: regression_model-webapp
        image: xerxez786/regression_model-webapp:latest
        ports:
        - containerPort: 8000   # Use port 3000


---
apiVersion: v1
kind: Service
metadata:
  name: regression_model-webapp-service
spec:
  selector:
    app: regression_model-webapp
  ports:
  - protocol: TCP
    port: 80               # Expose port 80
    targetPort: 8000
  type: LoadBalancer
