---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: training
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ttraining
  template:
    metadata:
      labels:
        app: training
    spec:
      containers:
      - name: training
        image: xerxez786/regression_model-webapp:latest
        ports:
        - containerPort: 8000   # Use port 3000

---
apiVersion: v1
kind: Service
metadata:
  name: training
spec:
  selector:
    app: training
  ports:
  - protocol: TCP
    port: 80                 # Expose port 80
    targetPort: 8000
  type: LoadBalancer
