---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: EKS_CLOUD
spec:
  replicas: 1
  selector:
    matchLabels:
      app: EKS_CLOUD
  template:
    metadata:
      labels:
        app: EKS_CLOUD
    spec:
      containers:
      - name: EKS_CLOUD
        image: xerxez786/regression_model-webapp:latest
        ports:
        - containerPort: 8000   # Use port 3000

---
apiVersion: v1
kind: Service
metadata:
  name: EKS_CLOUD
spec:
  selector:
    app: EKS_CLOUD
  ports:
  - protocol: TCP
    port: 80                 # Expose port 80
    targetPort: 8000
  type: LoadBalancer
