base:
  project: sarasconsultancy_mlops
  random_state : 20
  target_col: charges

data_source:
  s3_source: data/raw/insurance_preprossed.csv

load_data:
  raw_dataset_csv: data/raw/insurance_preprossed.csv

split_data:
  train_path: data/processed/train_insurance.csv
  test_path: data/processed/test_insurance.csv
  test_size: 0.2

estimators:
  ElasticNet:
    params:
      alpha: 0.7
      l1_ratio: 0.8

model_dirs: models/models.sav

reports:
  params: reports/params.json
  score: reports/scores.json

mlflow_config:
  artificats_dir: artifacts
  experiments_name: Elastic_Net
  run_name: mlops
  registered_model: ElasticNetMedicalExpenses
  remote_server_uri: 127.0.0.1:5000

